[build]
builder = "nixpacks"
buildCommand = "npm run build && cp -r public .next/standalone/public && cp -r .next/static .next/standalone/.next/static"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
