[build]
builder = "nixpacks"
buildCommand = "npm run build && cp -r public .next/standalone/dashboard-arkt-conseil/public && cp -r .next/static .next/standalone/dashboard-arkt-conseil/.next/static"

[deploy]
startCommand = "node .next/standalone/dashboard-arkt-conseil/server.js"
restartPolicyType = "on_failure"
